#Task1:

Create an inventory file /home/thor/playbook/inventory on jump host and add all app servers in it.
Create an Ansible playbook /home/thor/playbook/playbook.yml to install zip package on all app servers using Ansible yum module.
Make sure user thor should be able to run the playbook on jump host.

# inventory
stapp01 ansible_host=172.16.238.10 ansible_user=tony ansible_ssh_pass=Ir0nM@n
stapp02 ansible_host=172.16.238.11 ansible_user=steve ansible_ssh_pass=Am3ric@
stapp03 ansible_host=172.16.238.12 ansible_user=banner ansible_ssh_pass=BigGr33n

# Playbook.yml

---
- name: Install packages
  hosts: all
  become: yes
  tasks:
  - name: Install {{ packages }}
    yum: 
     name: "{{ packages }}"
     state: latest
    vars:
     packages:
       - zip

# Commands
ansible-playbook -i inventory playbook.yml
ansible all -i inventory -m shell -a "which zip"