# Create a playbook /home/thor/ansible/playbook.yml and add a task to create an empty file /tmp/file.txt on App Server 3

#Inventory file

stapp03 ansible_host=172.16.238.12 ansible_user=tony ansible_ssh_pass=BigGr33n

#playbook.yaml

- name: Create file in appserver
  hosts: stapp03
  become: yes
  tasks:
    - name: Create the file
      file:
        path: /tmp/file.txt
        state: touch

#Commands

# To list files in /tmp dir of a remote server before running playbook
ansible all -a "ls -ltr /tmp/" -i inventory

#To run playbook
ansible-playbook -i inventory playbook.yml